FROM docker.io/python:3.10.16-slim-bookworm

#set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

#set the working directory for any RUN, CMD, ENTRYPOINT, COPY and ADD instructions
WORKDIR /app

COPY . /app
RUN pip install -r requirements.txt

#Run sauce-man-bot
CMD ["python3", "main.py"]