services:
    sauce-man-bot:
        hostname: sauce-man-bot
        container_name: sauce-man-bot
        image: docker.io/focal1119/sauce-man-bot:2025-03-17-21-49
        restart: always
        # entrypoint: tail -f /dev/null
        env_file:
            - ./.env
        # network_mode: "host"